### ISSUE TITLE
not compatible with Cakephp 4.5

### ISSUE THREAD

**Issue by davalb** [salines/cakephp4-soft-delete#5]
In my project the soft-delete plugin stopped working with the update to cakephp 4.5.
The triggerBeforeFind Method is only executed with update queries and not select queries. Therefore the "deleted IS NULL" clause is not appended to the where-statement. I suspect it goes back to this change in 4.5: https://book.cakephp.org/4/en/appendices/4-5-migration-guide.html#orm-query-api-deprecations

**Comment by salines** [comment]
Hi,

please make a fork and your own repo with the changes. I'm sorry, I'm no longer able to upgrade these plugins. This repo will be archived. Thank you for understanding.
